---
git title: "Individual 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dat <- readxl::read_xls('GSS.xls')
library(dplyr)
library(ggplot2)
```

## R Markdown
cleaning the data with Mario's code

```{r}
#the cleaning mario did
data <- dat
str(data)
data$`Highest year of school completed` <- as.numeric(data$`Highest year of school completed`)
data$`Age of respondent` <- as.numeric(data$`Age of respondent`)
data$`R's age when 1st child born` <- as.numeric(data$`R's age when 1st child born`)
data$`Number of children` <- as.numeric(data$`Number of children`)
data <- data %>% na.omit
```

## Problem 5
```{r}

data$MarStatFact <- factor(data$`Marital status`, levels = c('Divorced','Married','Widowed','Never married','Separated', 'No answer'))

ggplot(data, aes(x=`Highest year of school completed`))+geom_bar() + facet_wrap(~ MarStatFact )

data %>% 
  group_by(MarStatFact) %>%
  summarize(mean_edu = mean(`Highest year of school completed`,na.rm=TRUE),
            sd_edu = sd(`Highest year of school completed`,na.rm=TRUE)) %>%
  arrange(mean_edu)
```


## Problem 6
```{r}

data$numPerInHouse <- factor(data$`Number of persons in household`, 1:12 )

ggplot(data, aes(x=`R's age when 1st child born`, fill = numPerInHouse))+geom_bar(color = 'black')+xlab("Age when First Child was Born")+ylab("count")+labs(fill = "Number of People in Household")+ggtitle("Age when First Child is Born by Number of People in Household")

ggplot(data, aes(x=`R's age when 1st child born`))+geom_bar() +facet_wrap(~ `Number of persons in household`, scales = 'free_y')+ggtitle("Age when First Child was Born Separated by Number of People in Household")

data %>%
  group_by(numPerInHouse) %>%
  summarize(mean_child = mean(`R's age when 1st child born`,na.rm=TRUE),
            sd_child = sd(`R's age when 1st child born`,na.rm=TRUE))
```